### DISCUSSION TITLE
3.3.0 版本发布

### DISCUSSION THREAD

**Discussion by wzpan** [wzpan/wukong-robot#210] [官方通知]
1. OpenAI 支持设置代理。提供了 `proxy` 和 `api_base` 两种方式来帮助用户解决 OpenAI 接口无法直接访问的问题。新的配置如下：

``` yaml
openai:
    openai_api_key: 'sk-xxxxxxxxxxxxxxxxxxxxxxxxxx'
    # 参数指定将生成文本的模型类型。默认情况下，OpenAI 提供了几个模型供您选择，您可以在此处查看。此外，您甚至可以创建自己的模型，但这超出了本教程的范围。https://beta.openai.com/docs/models/overview
    model: 'gpt-3.5-turbo'
    # 在前面加的一段前缀
    prefix: '请用200字回答：'
    # 该temperature参数指定响应的不确定性。这意味着该模型更有可能产生创造性的东西，并且可以被认为是模型承担风险并偏离正常反应。将此参数设置为 1 意味着模型将返回它不确定的结果，相比之下，将此参数设置为 0 意味着模型将返回它几乎可以肯定的结果。
    temperature: 1
    # 该max_tokens参数指定模型允许生成的最大字符数量作为其输出的一部分。您需要为生成的更多字符付费，因此请务必小心使用此参数。
    max_tokens: 2000
    # 一个可用于代替 temperature 的参数，对应机器学习中 nucleus sampling，如果设置 0.1 意味着只考虑构成前 10% 概率质量的 tokens
    top_p: 1.0
    # -2.0 ~ 2.0 之间的数字，正值会根据新 tokens 在文本中的现有频率对其进行惩罚，从而降低模型逐字重复同一行的可能性
    frequency_penalty: 0.0
    # -2.0 ~ 2.0 之间的数字，正值会根据到目前为止是否出现在文本中来惩罚新 tokens，从而增加模型谈论新主题的可能性
    presence_penalty: 0.0    
    stop_ai: 'stop'
    # 如果需要代理，反注释下面的配置进行修改
    # proxy: '127.0.0.1:1080'
    # 如果需要更换 api_base ，反注释下面的配置进行修改
    # api_base: "https://api.openai.com/v1/chat"
```

2. 新增 macOS 自带的 TTS 服务（非常快），使用 Mac 电脑的强烈推荐将 `tts_engine` 改为 `mac-tts`：

``` yaml
# 语音合成服务配置
# 可选值：
# han-tts       - HanTTS
# baidu-tts     - 百度语音合成（推荐）
# xunfei-tts    - 讯飞语音合成
# ali-tts       - 阿里语音合成（推荐）
# tencent-tts   - 腾讯云语音合成（推荐）
# azure-tts     - 微软语音合成
# mac-tts       - macOS 系统自带TTS（mac 系统推荐）
tts_engine: baidu-tts
```

同时 macOS TTS 也支持修改方言和音色：

``` yaml
# macOS 自带的 TTS 服务
# 注意：仅 macOS 系统可用！
mac-tts:
    # 命令行执行 say -v '?' 可以打印所有语音
    # 中文推荐 Tingting（普通话）或者 Sinji（粤语）
    voice: Tingting
```

3. 最低版本要求升级到 Python 3.7 及以上。使用了风格更优的字符串格式化写法替换了 `.format()` 语法。使用老版本 Python 的用户请升级。
