### DISCUSSION TITLE
3.5.1 版本发布 - 支持 edge-TTS 语音合成

### DISCUSSION THREAD

**Discussion by wzpan** [wzpan/wukong-robot#243] [官方通知]
### Bug Fixes

* 修复流式请求地址没有使用api_base的问题([#232](https://github.com/wzpan/wukong-robot/issues/232)) ([bb5a0ce](https://github.com/wzpan/wukong-robot/commit/bb5a0cea832009262675ab3b09ac0b5a16e9539f))

### Features

* 增加微软edge-tts文本转语音的支持([#233](https://github.com/wzpan/wukong-robot/issues/233)) ([727e4f4](https://github.com/wzpan/wukong-robot/commit/727e4f496dc2a5e915b93ed7ee4f8befb6cc8f69))

相关配置：

``` yaml
# 语音合成服务配置
# 可选值：
# han-tts       - HanTTS
# baidu-tts     - 百度语音合成（推荐）
# xunfei-tts    - 讯飞语音合成
# ali-tts       - 阿里语音合成（推荐）
# tencent-tts   - 腾讯云语音合成（推荐）
# azure-tts     - 微软语音合成
# mac-tts       - macOS 系统自带TTS（mac 系统推荐）
# edge-tts      - 基于 Edge 的 TTS（推荐）
tts_engine: edge-tts
```

同时 edge-tts 也支持修改方言和音色：

``` yaml
# 基于 edge 浏览器的在线 TTS 服务
edge-tts:
    # 命令行执行 edge-tts --list-voices 可以打印所有音色
    # 中文推荐 `zh` 开头的音色
    voice: zh-CN-XiaoxiaoNeural
```
