### DISCUSSION TITLE
3.5.2 版本发布 - 支持 VITS 文本转语音

### DISCUSSION THREAD

**Discussion by wzpan** [wzpan/wukong-robot#251] [官方通知]
### Bug Fixes

* 修改 edge-tts 的默认发音人为 `zh-CN-XiaoxiaoNeural` ([eba4ff7](https://github.com/wzpan/wukong-robot/commit/eba4ff7fbd5470200734184b706300361900ff12)) (#250 )

### Features

* 增加VITS文本转语音的支持 ([ca3566f](https://github.com/wzpan/wukong-robot/commit/ca3566fc87289a07282a9c526fb584edba111518)) (#248 )

VITS是一个可以通过输入语音数据集训练以克隆声线的AI文本转语音模型（原始项目：<https://github.com/jaywalnut310/vits>），加入对VITS的支持能够让智能音箱以用户自己喜欢的角色的声线来说话，增添趣味性。

相关配置：

``` yml
# 基于 VITS 的AI语音合成
VITS:
    # 需要自行搭建vits-simple-api服务器：https://github.com/Artrajz/vits-simple-api
    #    server_url: 服务器url（格式为http://{IP地址}:{端口}，不带最后的斜杠），如http://127.0.0.1:23456
    #    api_key: 若服务器配置了API Key，在此填入
    #    speaker_id: 说话人ID，由所使用的模型决定
    #    length: 调节语音长度，相当于调节语速，该数值越大语速越慢。
    #    noise: 噪声
    #    noisew: 噪声偏差
    #    max: 分段阈值，按标点符号分段，加起来大于max时为一段文本。max<=0表示不分段。
    #    timeout: 响应超时时间（秒），根据vits-simple-api服务器性能不同配置合理的超时时间。
    server_url: "http://127.0.0.1:23456"
    api_key: "api_key"
    speaker_id: 0
    length: 1.0
    noise: 0.667
    noisew: 0.8
    max: 50
    timeout: 60
```
