### ISSUE TITLE
如何使用 Wol 功能？

### ISSUE THREAD

**Issue by glk-hll** [wzpan/wukong-robot#186]
如何使用用户贡献技能 Wol，我在 .wukong/config.yml 中设置以下配置：
```yml
    # WOL启动
    wol:
        enable: true
        ip: '192.168.1.255'
        mac: 'B0-25-AA-2F-9E-EA'
```
然后输入指令：`开启电脑`，只有机器人返回的一些回答，请问问题出来哪里？是需要去下载这些插件使用吗？
