### ISSUE TITLE
勿扰模式自动打开

### ISSUE THREAD

**Issue by ZhangJun1015** [wzpan/wukong-robot#25]
硬件：树莓派3b+， ReSpeaker 4-Mic
唤醒词已经通过snowboy重新训练，并置于.wukong下面。
【问题】
唤醒悟空后，提问“深圳天气”，悟空还没有把深圳天气播报完，勿扰模式就自动打开了。
```
INFO:snowboy:Keyword 2 detected at time: 2019-02-28 17:27:53
2019-02-28 17:27:53,888 - __main__ - INFO - 勿扰模式打开
INFO:__main__:勿扰模式打开
```
```
# 勿扰模式，该时间段内自动进入睡眠，避免监听
do_not_bother:
    enable: false # 开启勿扰模式
    since: 23    # 开始时间
    till: 9      # 结束时间，如果比 since 小表示第二天
    on_hotword: '悟空别吵.pmdl'  # 通过这个唤醒词可切换勿扰模式。默认是“悟空别吵”
    off_hotword: '悟空醒醒.pmdl'  # 通过这个唤醒词可切换勿扰模式。默认是“悟空醒醒”
```
可是勿扰模式的设置是false啊，怎么回事？
