### ISSUE TITLE
同样的词有时候命中emotibot，有时候命中天气插件，怎么回事？

### ISSUE THREAD

**Issue by ZhangJun1015** [wzpan/wukong-robot#26]
硬件环境：树莓派3b+，ReSpeaker 4-Mic
【情景】唤醒悟空后，说“天气”两个字，后台百度识别为【天气，】，然后有时候被emotibot来回答，有时候又被weather插件回答，怎么回事？既然都是识别为【天气，】，为什么不是weather插件回答呢？
```
# 天气
# 使用心知天气的接口
# https://www.seniverse.com/
weather:
    enable: true
    key: 'mxyn5aekn8s4kcee'
    location: '深圳'
```
