### ISSUE TITLE
default.yml 里的默认邮箱配置项smtp_server与utils.py里获取的配置项server不匹配

### ISSUE THREAD

**Issue by lulee007** [wzpan/wukong-robot#6]
`static/default.yml：`
```yml
email:
    enable: true
    address: '你的邮箱地址'
    password: '你的邮箱密码'  # 如果是网易邮箱，须填写应用授权密码而不是登录密码！
    smtp_server: 'smtp.163.com'
```
但是发送邮件`robot/utils.py`里line 75 取的是`server`
```py

    password = config.get('/email/password', '')
    server = config.get('/email/server', '')
    port = config.get('/email/smtp_port', '')
```
最好也统一为`smtp_server`
```py
 server = config.get('/email/server', '')
```
