### ISSUE TITLE
关于wukong.pmdl

### ISSUE THREAD

**Issue by nameluck** [wzpan/wukong-robot#9]
在用户yml文件中

``` yml
# snowboy 离线唤醒
hotword: 'wukong.pmdl'  # 唤醒词模型，如要自定义请放到 $HOME/.wukong 目录中
sensitivity: 0.4  # 灵敏度
silent_threshold: 15 # 判断为静音的阈值。环境比较吵杂的地方可以适当调大
recording_timeout: 5 # 录制的语音最大长度（秒
```

在wukong.py中

``` py
 models = [
            constants.getHotwordModel(config.get('hotword', 'wukong.pmdl')),
            constants.getHotwordModel(utils.get_do_not_bother_on_hotword()),
            constants.getHotwordModel(utils.get_do_not_bother_off_hotword())
        ]
```

为什么有两处hotword的model呢，我把wukong.py中的hotmodel改成了wukong_pi.pmdl，用户yml文件中的hotword不变，依然可以用啊，不明白为啥有两处
